import test from 'node:test'
import assert from 'node:assert/strict'
import { reactive, nextTick } from 'vue'
import { loadVue, mount, content, nodes } from '../test-utils/vue.js'
const Panel = await loadVue(new URL('./NteRolesPanel.vue', import.meta.url))
const entries = Array.from({ length: 5 }, (_, i) => ({ id: String(i + 1), name: `角色${i + 1}`, quality: i ? 'A' : 'S', element: i ? '光' : '灵', level: i, awaken_level: 0, mix_level: 1, affinity_exp: 650, weapon: { name: '弧光', level: 30, quality: 'A', mix_level: 2 }, properties: [{ name: '攻击', value: '320' }], skills: [{ name: '战技一', level: 5 }], city_skills: [{ name: '城区一', level: 2 }] }))
const snap = (items = entries) => ({ payload: { schema_version: 1, entries: items }, stale: true, fetched_at: '2026-09-16T10:00:00+08:00' })
const button = (root, label) => nodes(root, 'button').find(n => n.props['aria-label'] === label)
const cards = root => nodes(root, 'li').filter(n => n.props.class?.includes('role-card'))
test('search and filter inputs update visible cards while retaining full role details', async t => {
  const root = mount(t, Panel, { snap: snap(), accountId: 'a' })
  assert.equal(cards(root).length, 5)
  for (const expected of ['羁遇累计经验 650', '弧光', '战技一', '城区一', '数据可能过期', '更新于']) assert.ok(content(root).includes(expected))
  nodes(root, 'input').find(n => n.props['aria-label'] === '搜索角色').props.onInput({ target: { value: '角色1' } })
  await nextTick(); assert.equal(cards(root).length, 1)
  assert.ok(content(cards(root)[0]).includes('角色1'))
  nodes(root, 'select').find(n => n.props['aria-label'] === '品质筛选').props.onChange({ target: { value: 'A' } })
  await nextTick(); assert.equal(cards(root).length, 0); assert.match(content(root), /没有符合/)
})
test('comparison keeps selections across filters, enforces four, removes selections, and needs two', async t => {
  const root = mount(t, Panel, { snap: snap(), accountId: '' })
  button(root, '对比角色1').props.onClick(); await nextTick()
  assert.match(content(root), /至少选择 2/); assert.equal(nodes(root, 'table').length, 0)
  for (const id of [2, 3, 4]) { button(root, `对比角色${id}`).props.onClick(); await nextTick() }
  assert.equal(button(root, '对比角色5').props.disabled, true)
  button(root, '对比角色5').props.onClick(); await nextTick()
  assert.equal(nodes(root, 'table').length, 1)
  nodes(root, 'input')[0].props.onInput({ target: { value: '角色5' } }); await nextTick()
  assert.match(content(nodes(root, 'table')[0]), /角色1.*角色2.*角色3.*角色4/)
  button(root, '移除对比角色2').props.onClick(); await nextTick()
  assert.equal(button(root, '对比角色5').props.disabled, false)
  assert.doesNotMatch(content(nodes(root, 'table')[0]), /角色2/)
})
test('element, sort direction and favorites filter control the card list', async t => {
  const previous = Object.getOwnPropertyDescriptor(globalThis, 'localStorage')
  Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { getItem: () => '["1"]', setItem() {} } })
  t.after(() => previous ? Object.defineProperty(globalThis, 'localStorage', previous) : delete globalThis.localStorage)
  const root = mount(t, Panel, { snap: snap(), accountId: 'a' })
  assert.match(content(cards(root)[0]), /角色5/)
  nodes(root, 'select').find(n => n.props['aria-label'] === '排序方向').props.onChange({ target: { value: 'asc' } }); await nextTick()
  assert.match(content(cards(root)[0]), /角色1/)
  nodes(root, 'select').find(n => n.props['aria-label'] === '元素筛选').props.onChange({ target: { value: '灵' } }); await nextTick()
  assert.equal(cards(root).length, 1)
  nodes(root, 'select').find(n => n.props['aria-label'] === '元素筛选').props.onChange({ target: { value: '' } })
  nodes(root, 'input').find(n => n.props['aria-label'] === '仅收藏').props.onChange({ target: { checked: true } }); await nextTick()
  assert.equal(cards(root).length, 1); assert.match(content(cards(root)[0]), /角色1/)
  button(root, '取消收藏角色1').props.onClick(); await nextTick(); assert.equal(cards(root).length, 0)
})
test('favorites survive remount, isolate accounts, and report unavailable storage without crashing', async t => {
  const previous = Object.getOwnPropertyDescriptor(globalThis, 'localStorage'), map = new Map()
  Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { getItem: k => map.get(k) ?? null, setItem: (k, v) => map.set(k, v) } })
  t.after(() => previous ? Object.defineProperty(globalThis, 'localStorage', previous) : delete globalThis.localStorage)
  const props = reactive({ snap: snap(), accountId: 'a' }), root = mount(t, Panel, props)
  button(root, '收藏角色1').props.onClick(); await nextTick()
  assert.ok(button(root, '取消收藏角色1'))
  const second = mount(t, Panel, { snap: snap(), accountId: 'a' })
  assert.ok(button(second, '取消收藏角色1'))
  props.accountId = 'b'; await nextTick(); assert.ok(button(root, '收藏角色1'))
  props.accountId = ''; await nextTick(); assert.equal(button(root, '收藏角色1').props.disabled, true)
  Object.defineProperty(globalThis, 'localStorage', { configurable: true, get() { throw Error('denied') } })
  props.accountId = 'c'; await nextTick(); assert.match(content(root), /收藏.*(读取|存储|保存)/)
  button(root, '收藏角色1').props.onClick(); await nextTick(); assert.match(content(root), /收藏.*(存储|保存)/)
})
test('legacy, empty, unsafe and failed portraits remain supported', async t => {
  assert.match(content(mount(t, Panel, { snap: null })), /暂无数据/)
  assert.match(content(mount(t, Panel, { snap: { payload: { raw: 1 } } })), /格式已更新/)
  assert.match(content(mount(t, Panel, { snap: snap([]) })), /暂无数据/)
  const root = mount(t, Panel, { snap: snap([{ name: '甲', icon_url: 'javascript:alert(1)' }, { name: '乙', icon_url: 'https://cdn.example.com/a.png' }]) })
  assert.equal(nodes(root, 'img').length, 1)
  const image = nodes(root, 'img')[0]; image.props.onError({ currentTarget: { src: image.props.src } }); await nextTick()
  assert.equal(nodes(root, 'img').length, 0)
})
